### ISSUE TITLE
Please add a list view or a hover mouseover method for seeing the full movie/episode/titlename

### ISSUE THREAD

**Issue by ctindel** [ttshivers/synclounge#127]
**Is your feature request related to a problem? Please describe.**
In the Grid View of a library the title names are shortened to just a few characters so if you have the same prefix name for a bunch of different titles you can't actually see which one is which.

**Describe the solution you'd like**
The plex web client provides a list view which would solve this problem.

**Describe alternatives you've considered**
Adding some sort of box that pops up with movie metadata when you hover over the image would also be a way to work around this problem, though who knows if it would be annoying to others when just moving their mouse around over a library.  Would have to play with it a little bit to see if this would work.

**Additional context**

**Comment by ttshivers** [comment]
I could implement both a tooltip in grid view and also add a list view. If I were to add a list view, what should the view toggle / style control button look like?

**Comment by ctindel** [comment]
I would just make it look like the Plex web client that toggles between grid and list view so the UI is consistent

**Comment by ttshivers** [comment]
What sort of columns would you be interested in having for a list view? I know Plex allows you to configure which ones you want, but to start off this feature, I'm going to just hardcode which ones.

**Comment by ctindel** [comment]
I don't know what the options are but the first column should be the full episode, movie, or filename I guess depending on the library type. Maybe also the resolution and file size in case people have multiple versions?

**Comment by ttshivers** [comment]
Should be resolved in https://github.com/ttshivers/synclounge/releases/tag/v3.11.0
