### ISSUE TITLE
SSO for organizr

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [ttshivers/synclounge#254]
**Is your feature request related to a problem? Please describe.**
SSO for organizr. I believe the original synclounge works with the existing myPlexAccessToken in the local storage of the domain.

**Comment by ttshivers** [comment]
Can you transfer this issue to https://github.com/synclounge/synclounge. My fork has now merged into the main repo

**Comment by Cookie-Monster-Coder** [comment]
Thank you so much for this! These new updates are fantastic!
